### ISSUE TITLE
Cannot change capitalization for symbols manually defined

### ISSUE THREAD

**Issue by bmuessig** [Vector35/binaryninja-api#1351]
Binary Ninja Version: 1.1.1555 Personal, 1d59e7dc
Platform: Ubuntu 18.04.2 LTS

I am not able to rename symbols previously defined manually to a different capitalization.
For instance `xml_writestringtag` cannot be renamed to `XML_WriteStringTag` even after resetting the symbol to its original sub%d form. I might suspect the error to be in the history combo box but I am not entirely sure. This is quite annoying if camel case is used and an error is made during renaming.

**Comment by rollsafe** [comment]
This seems to be Qt's fault because the dialog is choosing from the history case-insensitively.

**Comment by plafosse** [comment]
Should be fixed in 1.1.1790

**Comment by bmuessig** [comment]
I believe that it was not just the dialog box, because once you manage to enter a name in a different capitalization, it still won't rename. It's been a while though, since I opened the issue, so I will have another look.
