### ISSUE TITLE
Can't parse 64-bit number settings

### ISSUE THREAD

**Issue by 0x1F9F1** [Vector35/binaryninja-api#1392]
Binary Ninja Version: 1.1.1768-dev, 17231775
Platform: Windows 10 (10.0)

Trying to set a number setting (abstractLoader.entryPoint or abstractLoader.imageBase) over 0xFFFFFFFF in the UI doesn't work.

**Comment by bpotchik** [comment]
Interesting. I've been able to repro this for raw binaries using the MappedView only. Seems to work fine for Mach-O/ELF/PE.

**Comment by bpotchik** [comment]
Fixed in 1.1.1769-dev.

**Comment by 0x1F9F1** [comment]
So it's still broken, but it seems to be specific to Windows. I tested it on Linux and it works fine there.

**Comment by bpotchik** [comment]
Fixed in 1.1.1771-dev.

Also Windows platform related, #1394 is fixed in this build as well. This was a featured added almost a year ago.
