### ISSUE TITLE
Return type of Function is not honored, resulting in incorrect results

### ISSUE THREAD

**Issue by joshwatson** [Vector35/binaryninja-api#1430]
![image](https://user-images.githubusercontent.com/5834130/62839326-8d3b2000-bc3d-11e9-81cf-b7f5268c3cc9.png)
This function definitely sets a return value and returns it:
![image](https://user-images.githubusercontent.com/5834130/62839342-bfe51880-bc3d-11e9-8204-eb1bc4b48179.png)
And the return type of the function is `void**`. However, you can see above that the MLIL SSA is seeing the current value of `rax` as being the return value of a previously called function.

**Comment by plafosse** [comment]
I think this bug is fixed isn't it?

**Comment by joshwatson** [comment]
It's not fixed, here's the same binary in HLIL SSA form
![image](https://user-images.githubusercontent.com/5834130/80733774-011aa280-8ac3-11ea-8af0-b1e58be23862.png)

**Comment by plafosse** [comment]
Fixed in v2.0.2120
