### ISSUE TITLE
terminate called after throwing an instance of 'BinaryNinjaCore::DatabaseException'

### ISSUE THREAD

**Issue by jvdbroeck** [Vector35/binaryninja-api#1496]
Saving the database for a not-so-large but obfuscated ELF binary (14MB total, .text section 3.8MB) fails with the following error:
```
terminate called after throwing an instance of 'BinaryNinjaCore::DatabaseException'
  what():  Data too large
```
Ninja used at max 49.5GB RAM for this binary. Note that it has been heavily obfuscated.
I assume that it is related to #1267. Even though that issue is marked as fixed in version 1.1.1745-dev, I'm experiencing this error in version 1.2.1954-dev (Build ID af67f758).

Machine: AMD Ryzen Threadripper 2990WX 32-core (64GB RAM)

EDIT: In this case, BinaryNinja detected around 255M instructions (there are around 900k instructions in the binary, but lots of them are duplicated multiple times due to the applied obfuscations).

**Comment by janbbeck** [comment]
I am also experiencing this error with a particular binary, if I turn off tailcall options. After the initial analysis finishes, I start a bndb save, which proceeds to 100% and right at the end, the above error occurs.

Let me know if you need another binary to test against.

**Comment by negasora** [comment]
Fixed in 2.0.2218-dev

**Comment by janbbeck** [comment]
I still get this error, though with an extra `Aborted (core dumped)`. See #1774
