### ISSUE TITLE
Unicode strings not properly inlined in calls

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#1691]

**Comment by negasora** [comment]
Fixed in 2.0.2196-dev

**Comment by marpie** [comment]
I think that issue is not entirely fixed:

![image](https://user-images.githubusercontent.com/703785/83907617-01fbbf80-a766-11ea-9a5e-180a6d76d2ed.png)

![image](https://user-images.githubusercontent.com/703785/83907692-2192e800-a766-11ea-8ca7-f6a12519454a.png)

It seems to work for some binaries, but most of my test-binaries did not change. I did a fresh analysis (opened the binaries again, applied the PDB, etc.)

It even stays the same if I apply the following type:

```c
void  RtlInitUnicodeString(wchar16* DestinationString, wchar16 const* SourceString)
```

![image](https://user-images.githubusercontent.com/703785/83907971-95cd8b80-a766-11ea-9a45-2f50405ae4b6.png)

ENV:
Binary Ninja Version: 2.0.2197-dev, e01525df
Platform: Windows 10 Version 2004

**Comment by negasora** [comment]
The referenced data var needs to have the correct type. Try changing the type of that data var to `wchar16[25]`. It looks like the parameter type didn't get propagated, which #1456 is tracking.

**Comment by marpie** [comment]
It seems like that does not solve the issue ...

![image](https://user-images.githubusercontent.com/703785/83952341-946c9380-a838-11ea-9c4e-f8f307b2d153.png)
![image](https://user-images.githubusercontent.com/703785/83952397-f4fbd080-a838-11ea-991a-8dfde56c561d.png)

I defined the string manually (like you suggested va wchar16[25] and even applied the function.

Is there anything else I can try?

If you need a sample file, you can try this one:
https://msdl.microsoft.com/download/symbols/kerneltracecontrol.dll/3a2aa1f940000/kerneltracecontrol.dll

e.g. 0x1800134a8 (hlil) has a ref to 0x18002dd58 which is a utf-16 string.

**Comment by negasora** [comment]
The conditions for displaying unicode strings inline was too strict, that's fixed in 2.0.2200-dev, which will be out soon.

**Comment by marpie** [comment]
Thank you very much, the issue seems to be resolved now (tested with 2.0.2201-dev, 67ac368f).
