### ISSUE TITLE
Type parser parses zero-sized arrays as pointers

### ISSUE THREAD

**Issue by ExpHP** [Vector35/binaryninja-api#2434]
`bv.parse_type_string('char test[0]')` produces `char*` instead of `char[0]`.

This was working yesterday. #1999 looks very interesting. @plafosse?

---

2.3.2791-dev Personal

**Comment by plafosse** [comment]
Is this really problematic? They are essentially the same thing.

**Comment by D0ntPanic** [comment]
Fixed in build 3007

**Comment by plafosse** [comment]
Though the parser supports this notation HLIL still doesn't take this information into consideration. See: #2655
