### ISSUE TITLE
Stack Array Creation

### ISSUE THREAD

**Issue by d0mnik** [Vector35/binaryninja-api#2570]
**Binary Ninja Version**
2.4.2846 Personal

**Describe the bug**

Binary Ninja does not recognize an array access, resulting in the creation of stack variables, throwing off decompilation.

**To Reproduce**
1. View HLIL of `sub_8048b48`

**Screenshots**

<img width="447" alt="image" src="https://user-images.githubusercontent.com/32241418/127247471-1f0f25e7-ba27-41a7-b263-f486436d85cd.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/32241418/127247446-dfb849f0-da71-4898-96f6-6609549de64d.png">

Binary Ninja does not recognize that the `var_1c` array is being recognized and thus creates `var_20`, whose value is not set anywhere.

Hex-Rays more accurate decompilation:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/32241418/127247738-392893bd-b1a4-4564-ab3b-1dd52b673d78.png">

Binary Ninja also fails to recognize a stack variable being passed as arguments to a function call, resulting in inaccurate decompilation
<img width="552" alt="image" src="https://user-images.githubusercontent.com/32241418/127248803-f70156ec-4ae6-4e09-a9dc-e6d0a9fc40b6.png">
`esp_1` is throwing off the decompilation.

More accurate Hex-Rays decompilation:
<img width="552" alt="image" src="https://user-images.githubusercontent.com/32241418/127248909-a1c98178-ed6a-4da1-9b7b-768485d252c0.png">

**Version and Platform (required):**
 - Binary Ninja: Dev 2.4.2915 & 2.4.2846 Stable (if tested in stable, please also test the development channel via the "update channel" option)
 - OS: MacOS Big Sur
 - Version 11.5.1

**Additional context**
The binary can be found here:
https://drive.google.com/file/d/14X1Y7Dj4sn95giIKaKdbJJ6N6P1-n2mj/view?usp=sharing

**Comment by psifertex** [comment]
As a temporary fix for the second issue (which is caused by two different paths to the basic block at `0x8048a30` with different stack alignment) you can right-click on the branch at `0x80489bd` and select "always branch". You lose the first conditional, but it results in the stack being properly aligned which lets the function argument detection succeed for the remainder of the function. I don't know enough about the internal stack alignment calculation to know whether this is a bug or simply a missing analysis feature but I'll talk to others on the team.

Thanks for the detailed bug report.

**Comment by psifertex** [comment]
Actually after looking at it more closely, all of the stack mis-alignment functions in the  problem being reported here are due to the missing type information on printf. There is no 32bit libc type library currently so printf doesn't have the proper type information which is what is throwing off all the subsequent stack analysis. You can see that the 64bit version of the same file loads fine as in this example. 

[bomb.zip](https://github.com/Vector35/binaryninja-api/files/6897745/bomb.zip)

You can see the status of those libraries (which are actively being worked on) here: https://github.com/Vector35/binaryninja-api/issues/1495

**Comment by alloygoh** [comment]
Not quite sure why, but the decompilation of the 64bit binary doesnt quite look the same? It appears to be vastly different  from the Hex-Rays decompilation.

**Comment by psifertex** [comment]
I didn't have the exact source of the one you were using so I just searched for a different binary from CMU. Found this: http://csapp.cs.cmu.edu/3e/bomb.tar which may or may not be the same binary if that's what you mean?

**Comment by psifertex** [comment]
If you've got source to the 32bit one you had above and can rebuild as 64bit that should also show the correct stack alignment but there's so many different bomblab variants out there it's possible it's a different one.

**Comment by psifertex** [comment]
Though now that you mention it, comparing IDAs output on that sample they do decidedly worse on the main function. 

<img width="691" alt="Screen Shot 2021-07-29 at 12 07 49 AM" src="https://user-images.githubusercontent.com/140215/127429953-2e1dc8f7-5097-4d73-b9c5-323d6cff1038.png">
versus:
<img width="1045" alt="Screen Shot 2021-07-29 at 12 07 57 AM" src="https://user-images.githubusercontent.com/140215/127429966-ce8c4aae-4460-4ca1-a4c5-ef2189d2cbd6.png">

**Comment by alloygoh** [comment]
> I didn't have the exact source of the one you were using so I just searched for a different binary from CMU. Found this: http://csapp.cs.cmu.edu/3e/bomb.tar which may or may not be the same binary if that's what you mean?

Oh. I just naturally assumed it was the same bomblab but in 64bit, and wondered why the output was so different. Did not realize you were referring to the stack misalignment.

**Comment by plafosse** [comment]
Yeah the stack misalignment here is due to us getting the wrong parameter count for fopen. This would have been solved by type libraries or improvements on our stack resolution algorithm

**Comment by xusheng6** [comment]
This is also something peculiar in this binary. As we can see from the user's screenshot, he has already set the type of the stack variable `var_1c` to `int[0x6]`, butt the output still shows:

```
08048b79            void var_20
08048b79            result = (i + 1) * *(&var_20 + (i << 2))
```

A closer look up at the disassembly code reveals that the reason is the code references a location on the stack that is lower (address smaller) than var_1c, and we are not recognizing the pointer math to realize that it is actually referring to var_1c.

![Image](https://github.com/user-attachments/assets/1008f8b3-2532-4f6d-b043-48ad96529ddd)

This new aspect of the issue is actually #6199 and https://github.com/Vector35/binaryninja-api/issues/5406

**Comment by D0ntPanic** [comment]
Added in 5.0.7129
