### ISSUE TITLE
Show current function somewhere in UI

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#2988]
**What is the feature you'd like to have?**
I want to know what function I am currently inside of in my active pane within the UI.

**Is your feature request related to a problem?**
No.

**Are any alternative solutions acceptable?**
It doesn't matter to me *where* this information is visible, just that it *is* visible. It could be in the top bar of the pane (where we have the drop-downs for view type and stuff), it could be in the bottom-right where it shows the current selection, it could even just be an automatic scroll+highlight in the symbols pane (this might be annoying for other reasons, though). It just needs to be visible so I don't have to scroll the whole way to the top of my massive function to find the function name.

**Additional Information:**
Screenshot was provided in Slack. More than happy to provide more upon request.

**Comment by fuzyll** [comment]
We talked about this a little bit on Slack. I also like the idea of having the selection drop-down have "Show as..." and "Copy as..." as options that can be selected, rather than just having all of the copy options. A number of the copy options you can select could be useful to display in certain contexts instead of the current function.

**Comment by cxnder** [comment]
Was this resolved with #3453 ?

**Comment by fuzyll** [comment]
Yeah, we can go ahead and close this. There are probably some edge cases where the sticky titlebar doesn't quite solve the problem, but until I hit them, there's no sense leaving this open. I'll just re-open or make a new issue if/when those edge cases come up.
