### ISSUE TITLE
Opening and saving BNDB without taking any other action causes BNDB file to grow

### ISSUE THREAD

**Issue by galenbwill** [Vector35/binaryninja-api#3030]
**Version and Platform (required):**
- Binary Ninja Version: 3.0.3301-dev
- OS: macOS
- OS Version: 12.1

**Bug Description:**
Opening and saving BNDB without taking any other action causes BNDB file to grow, every time.

**Steps To Reproduce:**
1. Open a binary
2. Save and close the BNDB
3. Observe size of .bndb file
4. Open, save, and close BNDB
5. Observe size of .bndb file
6. Lather, rinse, repeat
 
**Expected Behavior:**
BNDB should not grow if no other action is taken.

**Screenshots:**
```
-rw-r--r--      360448 Mar 21 15:02 ls.bndb.0
-rw-r--r--     405504 Mar 21 15:03 ls.bndb.1
-rw-r--r--     446464 Mar 21 15:03 ls.bndb.2
-rw-r--r--     495616 Mar 21 15:04 ls.bndb.3
-rw-r--r--     495616 Mar 21 15:06 ls.bndb.4  <-- trimmed snapshots
-rw-r--r--     495616 Mar 21 15:06 ls.bndb.5  <-- saved again (without closing) after trimming
-rw-r--r--     409600 Mar 21 15:07 ls.bndb.6  <-- closed, reopened, and saved again
-rw-r--r--     409600 Mar 21 15:08 ls.bndb.7  <-- saved again (without closing)
-rw-r--r--     471040 Mar 21 15:08 ls.bndb.8  <-- closed, reopened, and saved again
```

**Additional Information:**
User reports growth of 40MB for an initially 70MB BNDB.

**Comment by v1X3Q0** [comment]
look forward to seeing this!

**Comment by CouleeApps** [comment]
A quick glance at this in the database browser shows the auto variable `__return_addr`'s `auto_defined` attribute is swapping between `true` and `false`: 
![image](https://user-images.githubusercontent.com/711973/159351758-ed16f2e6-6ce2-4bd9-8680-445879fdeb7e.png)

This means that every update has a different serialized form of the data and therefore the deduplication code doesn't do anything and you get another complete copy of the snapshot.

**Comment by fuzyll** [comment]
The specific comment above should be fixed in an upcoming dev build today. There are potentially some other discrepancies that @CouleeApps identified as well, though (like the count of `unresolved_indirect_branches`, I think). We should maybe do a slightly more thorough check before closing this.

**Comment by galenbwill** [comment]
Using 3305-dev, the situation has improved, but is not resolved:
```
-rw-r--r--      360448 Mar 22 12:32 ls.bndb.0
-rw-r--r--      393216 Mar 22 12:32 ls.bndb.1
-rw-r--r--      425984 Mar 22 12:33 ls.bndb.2
-rw-r--r--      425984 Mar 22 12:33 ls.bndb.3  <-- trim snapshots
-rw-r--r--      360448 Mar 22 12:34 ls.bndb.4  <-- after closing after trimming snapshots
-rw-r--r--      393216 Mar 22 12:34 ls.bndb.5   <-- saving again after trimming snapshots
```
So growth is still happening, but smaller. However, trimming snapshots now actually restores it to its original size.

**Comment by fuzyll** [comment]
I am no longer seeing this on @galenbwill's test executable with 3.0.3363-dev Enterprise. I'll try some other executables later today, but if I could get some feedback from other parties to this thread on whether this is sufficiently squashed, that'd be awesome.

Unless I run into an obvious case I can fix that I had missed earlier, or receive a good example of something else that is affecting `.bndb` file size, I will probably close this. There is ongoing work regarding database performance and I expect too much additional work on this might be wasted effort due to the amount of changes expected.

**Comment by fuzyll** [comment]
I've checked this out on a bunch of different executables now and I _believe_ the core issues that were causing this have now all been addressed. If I'm wrong, and anyone has a specific test case I can look into, please feel free to re-open this and I'll look into those specific cases further.
