### ISSUE TITLE
stdin / stdout is changed when importing binaryninja in IPython

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#392]
It appears that doing `import binaryninja` in IPython overwrites the way that it handles its stdin / stdout. As such there is no tab completion, backwards search, etc.. 

The code that is affecting it is:

``` python
# Wrap stdin/stdout/stderr for Python scripting provider implementation
sys.stdin = _PythonScriptingInstanceInput(sys.stdin)
sys.stdout = _PythonScriptingInstanceOutput(sys.stdout, False)
sys.stderr = _PythonScriptingInstanceOutput(sys.stderr, True)
```

This code should only be run when in Binary Ninja

**Comment by bambu** [comment]
For anyone interested. This is my current workaround/hack to be able to use both the BinaryNinja  and IPython interpreters:

```diff
diff --git a/python/__init__.py b/python/__init__.py
index 027c2a1..87f44e9 100644
--- a/python/__init__.py
+++ b/python/__init__.py
@@ -9905,7 +9905,10 @@ for name in core.all_enum_values:
 
 PythonScriptingProvider().register()
 
-# Wrap stdin/stdout/stderr for Python scripting provider implementation
-sys.stdin = _PythonScriptingInstanceInput(sys.stdin)
-sys.stdout = _PythonScriptingInstanceOutput(sys.stdout, False)
-sys.stderr = _PythonScriptingInstanceOutput(sys.stderr, True)
+try:
+    sys._getframe(1)
+except:
+    # Wrap stdin/stdout/stderr for Python scripting provider implementation
+    sys.stdin = _PythonScriptingInstanceInput(sys.stdin)
+    sys.stdout = _PythonScriptingInstanceOutput(sys.stdout, False)
+    sys.stderr = _PythonScriptingInstanceOutput(sys.stderr, True)
```

**Comment by plafosse** [comment]
I believe the problem is that you now need to specify logging to stdout `log_to_stdout(core.DebugLog)`
or in the future
`log_to_stdout(core.BNLogLevel.DebugLog)`
Reopen this ticket if this doesn't fix the issue.

**Comment by bambu** [comment]
The problem isnt about printing out to stdout. It is more so about using IPython to prototype scripts (since binaryninja's python console does not support niceties like tabcompletion, etc..). After I had experienced this issue I was able to reproduce related issues within binja (didn't document and dont remember how to reproduce currently) where code was assuming that stdout/stderr etc.. was a `file` object. Most commonly calling `flush` on stdout. 

IPython tends to `flush` to stdout a lot. Here's an example

```
In [1]: import binaryninja

In [2]: binaryninja.BinaryViewType['ELF']
Out[2]: <view type: 'ELF'>
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-1b09d3be0f03> in <module>()
----> 1 binaryninja.BinaryViewType['ELF']

/Library/Python/2.7/site-packages/ipython-5.1.0-py2.7.egg/IPython/core/displayhook.pyc in __call__(self, result)
    250                 self.write_format_data(format_dict, md_dict)
    251                 self.log_output(format_dict)
--> 252             self.finish_displayhook()
    253 
    254     def cull_cache(self):

/Library/Python/2.7/site-packages/ipython-5.1.0-py2.7.egg/IPython/core/displayhook.pyc in finish_displayhook(self)
    232         """Finish up all displayhook activities."""
    233         sys.stdout.write(self.shell.separate_out2)
--> 234         sys.stdout.flush()
    235 
    236     def __call__(self, result=None):

AttributeError: '_PythonScriptingInstanceOutput' object has no attribute 'flush'
```

The patch I provided is a bandaid fix. I think that the correct answer would be to either inherit from `file` or implement the standard functions that are in the `file` object.

**Comment by plafosse** [comment]
Ah, I see. I guess if you are running scripts from the command line we really shouldn't be stealing stdin/out/err

**Comment by plafosse** [comment]
I think this should work and is more canonical. 
```
if not sys.stdin.isatty():
	# Wrap stdin/stdout/stderr for Python scripting provider implementation
	sys.stdin = _PythonScriptingInstanceInput(sys.stdin)
	sys.stdout = _PythonScriptingInstanceOutput(sys.stdout, False)
	sys.stderr = _PythonScriptingInstanceOutput(sys.stderr, True)
```
Additionally, I will implement some of the standard file object functions.

**Comment by Manouchehri** [comment]
@bambu Thanks, your patch in https://github.com/Vector35/binaryninja-api/issues/392#issuecomment-242239609 worked for me.

**Comment by ColdHeat** [comment]
Just side commenting that plafosse's fix works as well in terms of using iPython.

**Comment by ColdHeat** [comment]
Also hijacking stdin/stdout/stderr without implementing the rest of the methods/attributes that are typically implemented leaves the Python console pretty stunted.

**Comment by plafosse** [comment]
This was fixed a while ago, by extending our Std/in/out/err replacements further.  We also created global variables containing: original_stdout, original_stdin, original_stderr, which can be used if there some issue we didn't foresee.

**Comment by plafosse** [comment]
Hmm looks like python already stores the original stdin/stdout/stderr in sys.__stdout__, sys.__stdin__, sys.__stderr__.  But I guess the original_stdout, etc variables are helpful in case of layered overriding of std*.

**Comment by atlas0fd00m** [comment]
looks like this one is still not finished.  ipython tab-complete and arrow-keys are handled incorrectly as soon as i import binaryninja.

**Comment by psifertex** [comment]
Looks like it's also caused by older ipythons. No workaround is required on a recent ipython. Older distros ship with `2.4` of ipython, but installing a newer version via:

```
sudo apt remove ipython
sudo apt install python-pip
pip install --upgrade pip
sudo pip install ipython
```
resulted in a version that works without any tweaks. `5.1.0` and `6.0` both appear to work in testing.
