### ISSUE TITLE
open_view / load APIs with invalid path are unhelpfully wrong

### ISSUE THREAD

**Issue by psifertex** [Vector35/binaryninja-api#4096]
If using any of the open_view or load APIs to load a file via CLI and you use a bad path, the error is incredibly unhelpful:

```python
>>> import binaryninja
>>> bv = binaryninja.load('/bogus')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/Binary Ninja-dev.app/Contents/Resources/python/binaryninja/__init__.py", line 335, in load
    raise Exception("Unable to create new BinaryView")
Exception: Unable to create new BinaryView
```

**Comment by bpotchik** [comment]
Fixed in `3.5.4458-dev`.

**Comment by pstirparo** [comment]
FYI, This is still happening in version 5
`CoreVersionInfo(major=5, minor=0, build=7290, channel='Stable')`
