### ISSUE TITLE
Reopening BNDB triggers analysis update

### ISSUE THREAD

**Issue by negasora** [Vector35/binaryninja-api#4596]
This bug was introduced in 3.5.4437-dev

**Steps To Reproduce:**
1. Open a BNDB created with the same version
2. See analysis happening

**Expected Behavior:**
Reanalysis shouldn't happen

**Screenshots:**
If applicable, please add screenshots here to help explain your problem.

**Additional Information:**
A binary that took 6 minutes for initial analysis has ~45 seconds of reanalysis after opening the bndb.
This doesn't happen in 3.4.4271.

**Comment by bpotchik** [comment]
Fixed in `3.5.4507`.

**Comment by alexrp** [comment]
This is still an issue for me on [this BNDB](https://drive.google.com/file/d/1KR7TumQyq9S5oDhbttDFaZ33i8qfL3AB/view?usp=sharing). BN always spends time reanalyzing when I open it. Seems to be a relatively recent phenomenon (last couple of weeks?).

**Comment by plafosse** [comment]
Reopening this issue while we look into this.

**Comment by alexrp** [comment]
Perhaps worth noting that the unexpected analysis doesn't take as long as an actual full reanalysis that happens due to a BN update. 🤔

**Comment by bpotchik** [comment]
There are three remaining sources of function reanalysis on BNDB load. These sources have been here for a while though, so the reanalysis behavior should be back to what it was on the previous stable.

- BinaryView::UpdateFunctionsForSymbolUpdate (Sourced from both BinaryView::Finalize and DefineAutoSymbol--->DefineSymbolInternal)
- callTypeAdjust information missing from the cached analysis
- function prototype information missing from the cache analysis
