### ISSUE TITLE
Binary Ninja fails to find entry point in OS X dylib

### ISSUE THREAD

**Issue by xmonk** [Vector35/binaryninja-api#462]
When loading a OS X dylib in Binary Ninja, the analysis works and finishes but it doesn't auto select the entry point as it does with .so libs.  In the python console running`bv.entry_point` returns `0L`.  I tested this with other dylibs and got the same behavior.  

Tested with Binary Ninja 1.0.7 Personal and Binary Ninja 1.0.dev-55 Personal.

**Comment by plafosse** [comment]
We recently fixed an issue with MachO parsing. Please retry to see if your issue is fixed. If it isn't please submit a test binary.

**Comment by bambu** [comment]
Verified on latest dev (1.0.804) with `/usr/lib/libnfrestore.dylib` that the issue still exists.

**Comment by plafosse** [comment]
Fixed in dev. This was the same issue as #461

**Comment by bambu** [comment]
This still does not seem to be fixed on latest dev (1.0.809). Verified that the same issue exists on `/usr/lib/libnfrestore.dylib` and `/usr/lib/ssh-keychain.dylib` (first two non FAT dylibs I found in /usr/lib).

**Comment by plafosse** [comment]
The Mach-O doesn't specify an entry point for these binaries. I guess we could select the function with the lowest address, but that kinda seems wrong too.

**Comment by mrexodia** [comment]
@gynophage enlightened me, these `.dylib` files are in a fat format that is not supported by binary ninja. You can extract the relevant architecture like this:

```
> lipo -info /usr/lib/libpthread.dylib 
Architectures in the fat file: /usr/lib/libpthread.dylib are: x86_64 i386
> lipo /usr/lib/libpthread.dylib -thin x86_64 -output ./libpthread.dylib.x86_64
```

And then you can load `libpthread.dylib.x86_64` in binary ninja.
