### ISSUE TITLE
Binary Ninja crashing when using Find

### ISSUE THREAD

**Issue by commonbreed** [Vector35/binaryninja-api#4854]
**Version and Platform (required):**
- Binary Ninja Version: 3.5.4526 Personal, ec37d737
- OS: windows
- OS Version: 11
- CPU Architecture: x86_64

**Bug Description:**
When running Find against a large bndb, the latest version of Binary Ninja is outright crashing on my system. It doesn't look like an OOM event, but Binary Ninja doesn't seem to have a comprehensive crash dump utility, so I'm not really sure how we're expected to give crash logs in these scenarios? The best I can do is give the Windows Error Reporting event details.

**Steps To Reproduce:**
Might not be able to reproduce on your side - open a large binary and run Find against some hex string.

**Expected Behavior:**
To complete the search.

**Screenshots:**

**Additional Information:**
From the Windows Error Report:

```
Faulting application name: binaryninja.exe, version: 3.5.4526.0, time stamp: 0x6504376e
Faulting module name: binaryninjacore.dll, version: 0.0.0.0, time stamp: 0x650436ac
Exception code: 0xc0000005
Fault offset: 0x0000000000799466
Faulting process id: 0x3874
Faulting application start time: 0x01da3ac84c0e5f28
Faulting application path: C:\Users\Ben\AppData\Local\Vector35\BinaryNinja\binaryninja.exe
Faulting module path: C:\Users\Ben\AppData\Local\Vector35\BinaryNinja\binaryninjacore.dll
Report Id: c4e018c5-cb67-4540-9917-c11c7d79bf6d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by negasora** [comment]
Does this repro with latest dev?

**Comment by commonbreed** [comment]
Just tried with Personal 3.6.4740-dev and the problem persists.

**Comment by xusheng6** [comment]
@commonbreed could you please share the binary so that I can reproduce it?

Also, in many cases, the "find" is not the best way to find code patterns. IL matching is better in many cases. I suggest you join our slack (https://slack.binary.ninja/) and ask us about it.

**Comment by psifertex** [comment]
We've been able to reproduce this and are getting the fix into the stable build that's just about to go out!

**Comment by plafosse** [comment]
Fixed in 4.0.4905

**Comment by zkxjzmswkwl** [comment]
Still happens consistently on 4.0.958. 

123mb binary. Searching for small values with "Find All" ticked = hangs.

**Comment by xusheng6** [comment]
> Still happens consistently on 4.0.958.
> 
> 123mb binary. Searching for small values with "Find All" ticked = hangs.
> 
> Win11 i7-14700k 64GB DDR5-5000MHZ

Hi @zkxjzmswkwl, thx for the report. Could you please share with us a binary that can trigger the issue?

**Comment by bpotchik** [comment]
Which find type is selected in the drop down? Can you try with the advanced search option?
