### ISSUE TITLE
Certain instructions have empty stack frames

### ISSUE THREAD

**Issue by CouleeApps** [Vector35/binaryninja-api#5602]
**Version and Platform (required):**
- Binary Ninja Version: 4.1.5489-dev
- OS: macOS
- OS Version: 14
- CPU Architecture: M1

**Bug Description:**
Some instructions in some functions incorrectly report having no live stack variables. When used with the new Position Aware Stack View, you get an empty screen.

**Steps To Reproduce:**
Please provide all steps required to reproduce the behavior:
1. Open this binary: [push-pop-automaton-macos.zip](https://github.com/user-attachments/files/15813286/push-pop-automaton-macos.zip)
2. Open stack view
3. Ensure Position Aware is enabled in the stack view context menu
4. Navigate to disassembly: 0x100003e59
5. Observe empty stack view

**Expected Behavior:**
I expected to see the stack variables present on the surrounding instructions, or really just anything at all.

**Screenshots/Video Recording:**
<img width="1117" alt="image" src="https://github.com/Vector35/binaryninja-api/assets/711973/3e016a3c-089d-441b-958f-7fa2c235847e">

**Additional Information:**
Disabling Position Aware shows the remaining frames. I figure that means the stack variable api is returning the wrong things, and that it's not an issue with Stack View itself.

**Comment by rssor** [comment]
Fixed today

**Comment by CouleeApps** [comment]
Seems like this still happens with "nop" instructions. Version 4.1.5742
<img width="1579" alt="image" src="https://github.com/user-attachments/assets/15925ca9-57bb-42cd-b50f-06c7b5136a1f">

**Comment by fuzyll** [comment]
The Stack view is _also_ empty if you select the function header or the closing/ending brace in Pseudo-C. Turning off "Position Aware" makes it show back up again.

**Comment by plafosse** [comment]
Fixed in 5.0.7290
