### ISSUE TITLE
Problem Outlining Stack Constructed Wide Strings

### ISSUE THREAD

**Issue by bpotchik** [Vector35/binaryninja-api#5652]
Version and Platform (required):

Binary Ninja Version: 4.1.558-dev
OS: macOS 15
CPU Architecture: m2
Bug Description:
Stack constructed wide strings are not being recovered properly.

I'm expecting the entire stack string to be correctly recovered.

Steps To Reproduce:
Please provide all steps required to reproduce the behavior:

Binary can be found internally with: `mention resolve access`.

Open binary
Go to `0x4020f8`

**Comment by bpotchik** [comment]
Fixed in `4.1.5569-dev`.

**Comment by seekbytes** [comment]
Hi! I'm the original submitter :) Problem still remain in `4.1.5569-dev`

![image](https://github.com/Vector35/binaryninja-api/assets/102438368/10d67b8c-2546-4408-9318-b67ca51e72cf)

**Comment by bpotchik** [comment]
There are a couple of other stack strings I found at `0x402948`, but they are related to a different issue. Check #5650 for reference.
