### ISSUE TITLE
Pasting multiple lines into python console only executes the first block

### ISSUE THREAD

**Issue by bambu** [Vector35/binaryninja-api#592]
When copying and pasting a script or multiple lines, only the first line/block of code is executed. It would be nice to be able to paste multiple blocks of code at a time. 

Ex:
```
>>> print "hello"
... print "world"
hello
>>>
```

**Comment by plafosse** [comment]
Fixed in dev 1.1.1026

**Comment by bambu** [comment]
The basic example works. However a more complicated example containing nesting seems to still fail.
```python
>>> a = 1
... if a == 1:
...     print('one')
... a = 2
... if a == 2:
...     print('two')
  File "<console>", line 3
    a = 2
    ^
SyntaxError: invalid syntax
```

**Comment by plafosse** [comment]
FYI This is the same way the standard python console works. Granted, in iPython this example does work.

**Comment by bambu** [comment]
Fair enough. I knew that this pattern worked in IDA and after it didn't work in binja i entered it in ipython and saw it work.
