### ISSUE TITLE
Width of operands to logical operations are mismatched in HLIL

### ISSUE THREAD

**Issue by fuzyll** [Vector35/binaryninja-api#6371]
**Version and Platform (required):**
- Binary Ninja Version: 4.3.6756-dev
- OS: macOS
- OS Version: 15.2
- CPU Architecture: aarch64

**Bug Description:**
At 0x0041ec5e in the provided x86_64 binary, the LHS of an `&` operation is 64-bit and the RHS is 32-bit, the result of which is stored in a 64-bit variable. Something similar occurs at 0x44a75c as well in a slightly more complicated scenario. In both cases, the `and` instruction appears to be using 32-bit values (using `ecx`, `edx`, and/or `eax`) in the instruction.

There are more at 0x463754 (`|`), and 0x43ce74 (`^`).

**Steps To Reproduce:**
1. Go to the addresses above
2. Observe the issue

**Expected Behavior:**
At 0x0041ec5e, for example, we should see the `zx.q` surround the entire rest of the line, since the assignment is to a 64-bit value.

**Screenshots/Video Recording:**

<img width="444" alt="Image" src="https://github.com/user-attachments/assets/da81e6bd-08eb-459f-b70f-f8ad1ceef01b" />

<img width="702" alt="Image" src="https://github.com/user-attachments/assets/f5521929-0f28-4e9a-b3e4-b8f2d5032701" />

**Binary:**
Vector 35 employees can search for _massive unruffled decoy curtain_ to find the binary.

**Additional Information:**
Reported by a user in our public Slack.

**Comment by plafosse** [comment]
@fuzyll Are you sure this is only in HLIL? Have you checked the constant size in LLIL/MLIL?

**Comment by seekbytes** [comment]
If I see correctly, the constant size in LLIL/MLIL seems sound (locally), as soon as we switch to HLIL (during upgrade of types from 32 to 64), the problem is presented. (source: I have binaries)

**Comment by xusheng6** [comment]
Binaries are provided in private to use. V35 folks should search for `purple ladder swift ocean candle` to find it

**Comment by negasora** [comment]
Fixed in `5.1.7477-dev`

**Comment by seekbytes** [comment]
I've noticed some other cases, would you mind if I ask to reopen this? 

```
(HLIL_VAR.b arg2) << (HLIL_CONST.d 1)
```

Binary: `brave wizard paints brightly` address `00400650`

**Comment by psifertex** [comment]
~Have you done some manual markup? When I try to reproduce that I see:~

```
00400600        return (0 - arg2) * arg1 + 0 - arg3
00400600            + (((arg2 << 1) * arg1) | arg3 << 1);
```

Having a conversation on slack about this, able to reproduce the syntax but still not sure what the mismatch is. I don't know that the width of the parameter/count of a shift necessarily needs to match the source width.

**Comment by plafosse** [comment]
This is working as expected. We take the approach that the RHS is implicitly ended with the size mask of the LHS. This is also how most architectures work.

**Comment by psifertex** [comment]
Re-opening and re-closing just so we can remove the "not planned" since the _first_ issue was indeed fixed and real and is on the 5.1 release.

**Comment by psifertex** [comment]
Re-opening and re-closing just so we can remove the "not planned" since the _first_ issue was indeed fixed and real and is on the 5.1 release.
