### ISSUE TITLE
Unresolved switch in iPhone18,4

### ISSUE THREAD

**Issue by withzombies** [Vector35/binaryninja-api#7429]
**Version and Platform (required):**
- Binary Ninja Version: 5.2.8309-dev, 9f2789c9
- OS: macos
- OS Version: 15.7
- CPU Architecture: arm64

**Bug Description:**
This switch is unresolved.

```
fffffe0008436564  mov     w16, w24
fffffe0008436568  cmp     x16, #0x3f
fffffe000843656c  csneg   x16, x16, xzr, ls  {0x0}
fffffe0008436570  adrp    x17, 0xfffffe0008437000
fffffe0008436574  add     x17, x17, #0x80  {sub_fffffe0008437080}
fffffe0008436578  ldrsw   x16, [x17, x16, lsl #0x2]
fffffe000843657c  adr     x17, data_fffffe000843657c
fffffe0008436580  add     x16, x17, x16
❓fffffe0008436584  br      x16
```

**Screenshots:**
<img width="939" height="484" alt="Image" src="https://github.com/user-attachments/assets/5a95e492-f9aa-44fd-bf85-e6db58beb5f7" />

**Binary:**
https://ipsw.me/install/iPhone18,4/23A341

**Comment by bdash** [comment]
In the same build, 5.2.8309-dev Ultimate (9f2789c9), I see that the jump table is detected and the control flow is resolved:

<img width="572" height="208" alt="Image" src="https://github.com/user-attachments/assets/81105b36-7731-4505-b7de-3301c4210a1a" />

I'm not sure why I'm seeing different results than you are.

Do you have any modified settings or plug-ins installed that could be relevant?

**Comment by withzombies** [comment]
Nope. I just reran the analysis and the jump still isn’t resolved. The
only change I’ve made is marking text:__const as r/w.

Cheers,
Ryan

**Comment by withzombies** [comment]
I was using a pre-existing bndb. When I re-created it, it detects the jump table. Would you like the old bndb?

**Comment by bdash** [comment]
I suspect you originally opened the kernelcache with a build older than 5.2.8235-dev (~3 weeks ago). That contains a fix for kernelcache memory regions had the incorrect permissions applied (https://github.com/Vector35/binaryninja-api/issues/7354). I see the behavior you reported if I open the kernelcache with 5.2.8233-dev, for instance.

To confirm, you can run the following in the Python console for both your existing bndb and the newly-opened kernel cache:
```
bv.memory_map.get_memory_region_flags(bv.memory_map.get_active_memory_region_at(0xfffffe0008437080))
```

Read, execute, and deny-write are what should be present. When opening with a build before 5.2.8235, you'll get an empty set (no permissions).

https://gist.github.com/bdash/b5b114300fd453569f9773335eb15cea is a script that I threw together that can be used to fix up the permissions in your existing database.

**Comment by withzombies** [comment]
```
>>> bv.memory_map.get_memory_region_flags(bv.memory_map.get_active_memory_region_at(0xfffffe0008437080))
... 
set()
```

seems so

**Comment by bdash** [comment]
I'm closing this as a duplicate of https://github.com/Vector35/binaryninja-api/issues/7354.

Feel free to reach out on Slack if you need any assistance with fixing up the permissions in your existing bndb.
