### ISSUE TITLE
Regression in split load/store 

### ISSUE THREAD

**Issue by utkonos** [Vector35/binaryninja-api#7647]
**Version and Platform (required):**
- Binary Ninja Version: 5.3.8622-dev Ultimate, 62a8cd21
- OS: macos
- OS Version: 15.7
- CPU Architecture: arm64

**Bug Description:**
This assembly is not accurately lifted to IL:

```
18001b53d  65488b03           mov     rax, qword [gs:rbx]
```

Here is the resulting LLIL:

```
  45 @ 18001b53d  rax = [gsbase + rbx {_TEB::ProcessEnvironmentBlock+3.q}].q
```

And HLIL:

```
18001b53d        TEB* gsbase
18001b53d        rax_4.b = gsbase->ProcessEnvironmentBlock.b
18001b53d        rax_4:1.b = gsbase->ProcessEnvironmentBlock:1.b
18001b53d        rax_4:2.b = gsbase->ProcessEnvironmentBlock:2.b
18001b53d        rax_4:3.b = gsbase->ProcessEnvironmentBlock:3.b
```

This causes more problems downstream because `rax_4` is not of type `PEB*`

<img width="581" height="153" alt="Image" src="https://github.com/user-attachments/assets/c24231da-1116-4bd1-a132-e63664207f9f" />

**Steps To Reproduce:**
Open the database or binary and look at `0x18001b53d`

BNDB: `dense atom prunes validly`
Binary: `dual yard releases fractally`

**Expected Behavior:**
HLIL should be:

```
rax_4 = gsbase->ProcessEnvironmentBlock
```

**Screenshots:**
Setting `rax_4` manually to type `PEB*` fixes most of the downstream problems (remaining problems listed below):

<img width="557" height="129" alt="Image" src="https://github.com/user-attachments/assets/8ade53ab-7eb6-4421-8603-f27dd0680720" />

Even after manually setting the type of `PEB*`, this instruction is missing an annotation. Downstream instructions do get correct annotations, but this one is still missing:

<img width="670" height="206" alt="Image" src="https://github.com/user-attachments/assets/f38e2e05-78b1-43a3-97ab-ea1160dff6c6" />

**Comment by rssor** [comment]
This is fixed on dev, I can pull in the commit/build number later when I'm at a computer again. There's several of these to close, actually.

**Comment by rssor** [comment]
Fixed in 5.3.8689.

**Comment by utkonos** [comment]
@rssor This looks good. Thanks. It didn't fix the bug with relative offsets in the loader linked lists in issue #7648 however. I think that's due to an incomplete fix to #6492 

<img width="554" height="95" alt="Image" src="https://github.com/user-attachments/assets/98681ecc-71df-4ecd-a085-ea46fe0f87d1" />

**Comment by rssor** [comment]
Yeah that's something worse, I'm taking a look at it now.

**Comment by rssor** [comment]
Oh, nope, it's nowhere near as bad, just the offsets being wrong like you said.

**Comment by utkonos** [comment]
FYI: If you have the above issue, and you also have a version of Binja where all the underlying fixes have been implemented, to get a function looking as expected there are a few steps needed. That's all here:

https://github.com/Vector35/binaryninja-api/issues/7769#issuecomment-3647833415
