### ISSUE TITLE
64-bit bswap lifted incorrectly

### ISSUE THREAD

**Issue by amatus** [Vector35/binaryninja-api#950]
The x86_64 instruction
```
bswap rax
```
is lifted to the Lifted IL operations
```
temp0.q = (rax & 0xff) << 0x38
temp1.q = (rax & 0xff00) << 0x28
temp2.q = (rax & 0xff0000) << 0x10
temp3.q = (rax & 0xff000000) << 8
temp4.q = (rax & 0xff00000000) u>> 8
temp5.q = (rax & 0xff0000000000) u>> 0x10
temp6.q = (rax & 0xff000000000000) u>> 0x28
temp7.q = (rax & 0xff00000000000000) u>> 0x38
rax = temp0.q | (temp1.q | (temp2.q | (temp3.q | (temp4.q | (temp5.q | (temp6.q | temp7.q))))))
```
it should be
```
temp0.q = (rax & 0xff) << 0x38
temp1.q = (rax & 0xff00) << 0x28
temp2.q = (rax & 0xff0000) << 0x18
temp3.q = (rax & 0xff000000) << 8
temp4.q = (rax & 0xff00000000) u>> 8
temp5.q = (rax & 0xff0000000000) u>> 0x18
temp6.q = (rax & 0xff000000000000) u>> 0x28
temp7.q = (rax & 0xff00000000000000) u>> 0x38
rax = temp0.q | (temp1.q | (temp2.q | (temp3.q | (temp4.q | (temp5.q | (temp6.q | temp7.q))))))
```

**Comment by psifertex** [comment]
Thanks for the report. Fixed in build 1062.

**Comment by joshwatson** [comment]
Something is still broken with how this is being lifted.

```
>>> bv.get_disassembly(here)
'bswap   rax'
>>> current_mlil.ssa_form[8]
<il: rax#1 = temp0#1 | (temp1#1 | (temp2#1 | (temp3#1 | (temp4#1 | (temp5#1 | (temp6#1 | temp7#1))))))>
>>> for var in current_mlil.ssa_form[8].vars_read:
... 	print var, current_mlil.ssa_form[8].get_ssa_var_possible_values(var)
... 
<ssa <var int64_t temp0> version 1> <unsigned ranges: [<range: 0x0 to 0xff00000000000000, step 0x100000000000000>]>
<ssa <var int64_t temp1> version 1> <unsigned ranges: [<range: 0x1000000000000 to 0xff000000000000, step 0x1000000000000>]>
<ssa <var int64_t temp2> version 1> <unsigned ranges: [<range: 0x10000000000 to 0xff0000000000, step 0x10000000000>]>
<ssa <var int64_t temp3> version 1> <unsigned ranges: [<range: 0x100000000 to 0xff00000000, step 0x100000000>]>
<ssa <var uint64_t temp4> version 1> <unsigned ranges: [<range: 0x1000000 to 0xff000000, step 0x1000000>]>
<ssa <var uint64_t temp5> version 1> <unsigned ranges: [<range: 0x10000 to 0xff0000, step 0x10000>]>
<ssa <var uint64_t temp6> version 1> <unsigned ranges: [<range: 0x100 to 0xff00, step 0x100>]>
<ssa <var uint64_t temp7> version 1> <unsigned ranges: [<range: 0x1 to 0xff>]>
```

Each of these `tempX` Variables should have a possible values range of `[<range: 0x0 to 0xff...., step ....>]`. As it stands, dataflow currently considers it impossible for `rax#1` to be `0`, which is clearly not the case.

**Comment by plafosse** [comment]
Yeah this looks like a data flow bug rather than a lifting bug.

**Comment by joshwatson** [comment]
I'll make it a new issue since it's a different type of bug
