### ISSUE TITLE
LLIL wrong stack emulation with inline pop

### ISSUE THREAD

**Issue by f0rki** [Vector35/binaryninja-api#999]
I noticed inconsistencies when lifting to LLIL and using "inline" pop instructions. The stack pointer offset seems to be not properly adjusted, when I use pop as part of another LLIL sub-expression. When using `set_reg` and `LLIL_TEMP` registers, everything works as expected.

Version: `1.1.1139-dev Personal (Build ID 9959f571)`

Background: I've been playing a little with a custom Architecture for the [ethereum vm](https://github.com/trailofbits/ethersplay) plugin. I improved LLIL lifting and tried to use the emulation to propagate constant values (my progress is [here](https://github.com/f0rki/ethersplay/tree/llil_lifting)).

I lifted the following LLIL. The comment shows how the stack should look like after the instruction (all stack slots are 32-byte).
![2018-03-25-122733_601x66_scrot](https://user-images.githubusercontent.com/617306/37878697-4dc154ce-306d-11e8-8b74-5f7dc8b2aeb7.png)

I then use the `function.get_stack_contents_after` function to explore the stack:

```
>>> f.get_stack_contents_after(0x56, -32 * 4, 32)
<const 0x4>
>>> f.get_stack_contents_after(0x56, -32 * 5, 32)
<const 0x20>
>>> f.get_stack_contents_after(0x56, -32 * 6, 32)
<const 0x24>
```

As you can see this is not what I expected. It seems the pops do not properly adjust the stack pointer. I changed the lifting code to use temporary registers. Then everything works as expected:  
![2018-03-25-203627_597x70_scrot](https://user-images.githubusercontent.com/617306/37878728-abc9a92c-306d-11e8-8b4b-bf76d7a980c1.png)

```
>>> f = bv.get_function_at(0x42)
>>> f.get_stack_contents_after(0x56, -32 * 4, 32)
<const 0x24>
>>> f.get_stack_contents_after(0x56, -32 * 5, 32)
<const 0x20>
>>> f.get_stack_contents_after(0x56, -32 * 6, 32)
<undetermined>
```

I noticed the same issue also for other instructions. In this case a conditional branch with a inline pop expression. The last instruction of the basic block here:
![2018-03-25-120852_737x184_scrot](https://user-images.githubusercontent.com/617306/37878744-e1b91112-306d-11e8-96fb-5dc96e00c0da.png)
Here the stack pointer offset tracking is also wrong, i.e. the pop doesn't seem to actually adjust the stack pointer offset.
```
>>> f = bv.get_function_at(0x42)
>>> f.get_reg_value_after(0x46, 'sp')
<stack frame offset -0x20>
```

As a workaround I used a temporary register again and then everything works as expected.
![2018-03-25-205645_598x193_scrot](https://user-images.githubusercontent.com/617306/37878837-272f3e0a-306f-11e8-9656-1d37b1ae21c1.png)

```
>>> f = bv.get_function_at(0x42)
>>> f.get_reg_value_after(0x46, 'sp')
<stack frame offset 0x0>
```

This seems like a bug to me. Or is the pop expression supposed to work differently when used within another expression? Is there potentially something missing in the custom Architecture plugin?

**Comment by rssor** [comment]
Taking a quick look at things, I think this is a quirk of how we're performing the dataflow query right now. If you look at the SSA or mapped MLIL views of the IL, the tracking *should* be correct. Using the regular `get_reg_value` method on the *next* LLIL instruction should also return the expected stack offset.

I'll look into this more tomorrow -- it's definitely not something missing from the Architecture plugin.

**Comment by f0rki** [comment]
OK let's stick to the add example:

```
>>> x = f.get_low_level_il_at(0x56)
>>> x
<il: push.32(pop.32 + pop.32)>
```

When I look at the SSA form, the sp tracking is wrong:

![2018-03-26-104942_1219x46_scrot](https://user-images.githubusercontent.com/617306/37896261-b0dbfd54-30e3-11e8-8b37-5d45cf7f2038.png)

```
>>> x = f.get_low_level_il_at(0x56)
>>> x
<il: push.32(pop.32 + pop.32)>
>>> x.ssa_form
<il: [sp#13.33 - 0x20].32 = [sp#13.33 + 0x20].32 @ mem#12 + [sp#13.33].32 @ mem#12 @ mem#12 -> mem#13>
```

Here `sp#13` is the stack pointer from the previous instruction. However, the right-hand sind of the expression is supposed to modify the `sp`. i.e. correct would be `sp#13 + 0x20` in this case.

If I use more than one LLIL instruction, with temp registers, I get the following SSA form. The stack pointer is properly adjusted after every of the `set_reg` instructions:

![2018-03-26-105111_899x135_scrot](https://user-images.githubusercontent.com/617306/37896295-c8274ac2-30e3-11e8-9c55-d54251009722.png)

**Comment by rssor** [comment]
Thanks, that being wrong was a core bug. It's fixed in build 1.1.1140-dev.

This build will not address the behavior you were seeing with `get_reg_value_after`, though.

**Comment by f0rki** [comment]
Nice! Thank you very much :)

**Comment by f0rki** [comment]
But what I don't get is why the other behaviour is still wrong? You said that it's because of the way you do data-flow queries, but to me this seems like the same bug?

Let me explain. So I'm lifting a conditional branch to the following LLIL:

![2018-03-27-103225_985x154_scrot](https://user-images.githubusercontent.com/617306/37956209-f8ce06bc-31aa-11e8-9265-b12f6ef4919c.png)

As you can see there are two `pop` instructions there. When I look at the SSA form:
![2018-03-27-103247_930x90_scrot](https://user-images.githubusercontent.com/617306/37956256-1780e61a-31ab-11e8-9ab1-0b433168a3ea.png)
![2018-03-27-103254_509x74_scrot](https://user-images.githubusercontent.com/617306/37956262-1998de58-31ab-11e8-8e6b-1118ca3853cd.png)
![2018-03-27-103301_359x64_scrot](https://user-images.githubusercontent.com/617306/37956265-1bafaa00-31ab-11e8-8375-e067d16e9b12.png)

Then again the `sp` is only adjusted once for the first `pop` instruction. The `pop` that is inlined into the `if_expr` is accessing the right stack slot, but does not adjust the stack pointer.

**Comment by joshwatson** [comment]
Dataflow doesn’t work with 32 byte sizes

**Comment by rssor** [comment]
That has less to do with dataflow and more with the fact that several expressions (LLIL_IF, LLIL_JUMP, LLIL_CALL) aren't allowed to have sub-expressions that have side effects right (flag write types, LLIL_POP) now. We place the stack pointer adjustment after the instruction that caused it, and if the original instruction moves control flow to move elsewhere it either won't run the fixup or will run it after the called function returns.

The solution is to not have side effects within those particular expressions -- the core should probably perform this transformation automatically, but right now there aren't bumper guards to protect against this.

**Comment by f0rki** [comment]
@rssor good to know. maybe this could be added to the documentation? 

@joshwatson simple constant propagation seems to work.

**Comment by plafosse** [comment]
Looks like this issue has been resolved.
